### ISSUE TITLE
jq & yq no longer available?

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/image-cli-tools#23]
Following the instructions in the readme & it looks like jq & yq are no longer available in the cli-tools image...

![image](https://user-images.githubusercontent.com/974294/152285700-0d60067b-64af-40e2-b449-1c5bc3debed8.png)

I noticed this when executing a job inside a cluster using the `v0.15` image, and `jq` is not available, despite the fact that I see it in the [Dockerfile](https://github.com/cloud-native-toolkit/image-cli-tools/blob/v0.15/Dockerfile#L103).

**Comment by seansund** [comment]
@triceam You are using a very old version of the container image. The most current version of the image is published at `quay.io/cloud-native-toolkit/cli-tools`.

If you take `latest` you will get terraform v1.1. If you want a different version of terraform, use the tag that corresponds with the terraform version:

- terraform v1.1.x - `quay.io/cloud-native-toolkit/cli-tools:v1.1` (or `quay.io/cloud-native-toolkit/cli-tools:latest`)
- terraform v1.0.x - `quay.io/cloud-native-toolkit/cli-tools:v1.0`
- terraform v0.15 - `quay.io/cloud-native-toolkit/cli-tools:v0.15`
- terraform v0.14 - `quay.io/cloud-native-toolkit/cli-tools:v0.14`

**Comment by seansund** [comment]
Looking at the README, I can see the issue. The README hasn't been updated in some time. Being addressed in #33
